name: Generate Code
on: 
  push:
    branches: 
    - codegen

jobs:
  build:
    name: Generate Code
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: codegen
      - uses: actions/setup-java@v1
        with:
          java-version: '13' 
          java-package: jdk 
          architecture: x64 
      - run: |
          wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.14/swagger-codegen-cli-2.4.14.jar \
            -O swagger-codegen-cli.jar
          java -jar swagger-codegen-cli.jar generate \
            -l python --git-user-id nrfta --git-repo-id ${{ github.repository }} \
            -c config.json -i netbox.swagger -o cd $GITHUB_WORKSPACE/master
          cd $GITHUB_WORKSPACE/master 
          /bin/sh ./git_push.sh nrfta python-netbox-client "Code generated release"

